services:
  atuin:
    image: ghcr.io/atuinsh/atuin:v18.4.0
    command: server start
    volumes:
      - atuin_config:/config
    environment:
      ATUIN_HOST: "0.0.0.0"
      ATUIN_OPEN_REGISTRATION: "false"
      ATUIN_DB_URI: postgres://$ATUIN_DB_USERNAME:$ATUIN_DB_PASSWORD@$ATUIN_DB_HOST/$ATUIN_DB_NAME
      RUST_LOG: info,atuin_server=debug

volumes:
  atuin_config: