services:
  atuin:
    image: ghcr.io/atuinsh/atuin:v18.4.0
    command: server start
    volumes:
      - atuin_config:/config
    environment:
      RUST_LOG: info,atuin_server=debug

volumes:
  atuin_config:
